#!/usr/bin/env bash

set -euxo pipefail

export SAPINAA_DEBUG=1

# Create debug data if it doesn't exist
if [[ ! -f "./test/testfeeds.json" ]];
then
    cp "./test/testfeeds.json.template" "./test/testfeeds.json"
fi
if [[ ! -f "./test/testfeedsdata.json" ]];
then
    npm run cache-requests
fi

# Bundle client
(
  cd reader
  parcel build main.html --public-url ./
)

# Start electron
exec npm run dev
