#!/usr/bin/env bash

set -euxo pipefail

rm -Rf build
mkdir build
cd build

cp -R ../reader .
cp "../package.json" .
../scripts/rename-package-json.js "./package.json" | sponge "./package.json"

../scripts/bundle "reader/main.html"

electron-packager . sapinaa --electron-version=v7.1.1
